# NOTE: don't name any entities "eventstore*", as this will create env vars like
#   EVENTSTORE_* within the pods and eventstore docker container will assume it
#   to be a config directive and thus will fail with "unknown config parameter"
#   error

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evstore-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: evstore
spec:
  selector:
    matchLabels:
      run: evstore
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        run: evstore
    spec:
      initContainers:
      - name: init-evstore
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 1000:1000 /var/lib/eventstore']
        volumeMounts:
        - name: evstore-data
          mountPath: "/var/lib/eventstore"
          readOnly: false
      containers:
      - name: evstore
        image: eventstore/eventstore:21.10.1-bionic
        # imagePullPolicy: IfNotPresent
        # command: ['sh', '-c', 'set; echo; id; echo; /opt/eventstore/eventstored']
        args:
        - '--insecure'
        - '--run-projections=All'
        - '--disable-log-file'
        volumeMounts:
        - name: evstore-data
          mountPath: "/var/lib/eventstore"
          readOnly: false
      volumes:
      - name: evstore-data
        persistentVolumeClaim:
          claimName: evstore-data

---

apiVersion: v1
kind: Service
metadata:
  name: evstore-service
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    run: evstore
  ports:
  - name: evstore-http
    protocol: TCP
    port: 2113
    targetPort: 2113
    nodePort: 30250
  - name: evstore-tcp
    protocol: TCP
    port: 1113
    targetPort: 1113
    nodePort: 30251
