apiVersion: v1
kind: Service
metadata:
  name: eventstore-service
spec:
  type: LoadBalancer
  selector:
    run: eventstore
  ports:
    - protocol: TCP
      port: 2113
      targetPort: 2113
      #nodePort: 30001

